Mission 1
waterhumanB/js-number-up-and-down pull request #1
Opened 2024-11-10 04:17 UTC by waterhumanB

일단 모든 동작은 구현했습니다. 제일 고민했던 부분은 "함수(또는 메서드)의 들여쓰기는 2단계까지만 허용한다." 이부분으로 게임을 reset하는 부분을 함수로 구현해 play 함수를 콜백으로 받게끔 해서 재시작 또는 종료하게 만들었습니다.

궁금한점은 while문 부분도 함수로 뺄 수가 있을까? 아니면 빼야 할까? 이런 고민이 있습니다. 코드가 조금 지저분해 보이는거 같기도 합니다. 요구사항에 콜백함수와 클로저를 활용하라고 되어있는데, 콜백함수는 사용은 했지만 맞는 의도인지 모르겠고, 클로저 같은 경우 제가 구현한 코드에서 클러저를 사용할곳이 없다는? 생각이 들었고, 만약 사용해야한다면 함수를 분리해서 해야할것 같은데, 굳이 함수로 분리해서 클로저를 이용해야하는건지? 아니면 이대로 구현해도 되는지 궁금합니다.

2024-11-10 11:35 UTC, hansen-dev requested changes
안녕하세요 수인님 고생 많으셨어요!

코멘트 남긴 내용 반영해서 다시 리뷰 요청해주실 수 있을까요?

추가로 질문에 대한 답변을 드려볼게요.

> 궁금한점은 while문 부분도 함수로 뺄 수가 있을까? 아니면 빼야 할까? 이런 고민이 있습니다. 

뺄려면 뺄 수는 있지만 지금 상황에서는 반드시 빼야 할 필요는 없을 것 같아요. 
특히 들여쓰기 2단계 조건 때문에 빼는 경우는 더욱 없을 듯 하구요.
다만 나중에 상황에 따라 `하나의 함수는 하나의 기능만 수행하도록 한다` 조건에 의해 나눌 수는 있을 것 같네요!

> 코드가 조금 지저분해 보이는거 같기도 합니다.

요 부분은 왜 지저분하다 느끼셨을까요? 
이렇게 느낀 이유가 궁금해요.

> 요구사항에 콜백함수와 클로저를 활용하라고 되어있는데, 콜백함수는 사용은 했지만 맞는 의도인지 모르겠고, 클로저 같은 경우 제가 구현한 코드에서 클러저를 사용할곳이 없다는? 생각이 들었고, 만약 사용해야한다면 함수를 분리해서 해야할것 같은데, 굳이 함수로 분리해서 클로저를 이용해야하는건지? 아니면 이대로 구현해도 되는지 궁금합니다.

해당 부분에 대한 답변으론 만약 필요성을 느끼지 못했다면 지금 당장 굳이 쓰지 않으셔도 돼요.
요구사항에 적혀있는 것 처럼 필요한 경우에 사용하시면 됩니다!

만약 어떨때 클로저 또는 콜백 함수를 쓰면 좋을지? 고민이 된다면 클로저, 콜백 함수는 각각 어떨때 쓰면 좋은지? 한번 고민해보시면 좋을 것 같아요.


전반적으로 조금 더 고민해보시고 만약 그럼에도 잘 모르겠다면 이후 티타임때 이야기 나눠보면 좋겠어요! (일단 위 피드백은 모두 반영 후 다시 리뷰 요청주세요!)

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +play();
P5;
End of file 줄여서 eof 라고 하는 말을 아시나요?
VSCode 등의 요즘의 IDE에서는 큰 문제없이 잘 동작되지만 환경에 따라 파일 끝에 줄바꿈이 되지 않으면 의도와 다르게 빌드가 안되는 현상이 발생할 수 있어요!
혹시모를 상황을 대비해서 항상 파일 끝에는 줄바꿈을 해주시는 것을 추천드려요!
이를 해결하기 위해 각 IDE에 eof 설정을 추가하거나 editorConfig를 사용해요!

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +async function play() {
P1;

현재 **프로그래밍 요구사항**의 `함수는 10라인 이내로 작성하며, 하나의 함수는 하나의 기능만 수행하도록 한다.` 규칙을 어긴 것 같아요.

꼭 10라인 이내는 아니더라도 지금보단 더 줄일 수 있을 것 같은데 개선시켜 볼 수 있을까요?
(해당 요구사항의 의도를 이해해보시면 좋을 것 같아요.)

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +  if(resetGame != "yes" && resetGame != "no") {
P2;

가독성을 위해 space를 넣으면 좋을 것 같아요.
```suggestion
  if (resetGame != "yes" && resetGame != "no") {
```

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +  if(resetGame != "yes" && resetGame != "no") {
ask;

얕은 비교와 깊은 비교 둘의 차이에 대해 알고 계신가요!?
저는 개인적으로 정말 특수한 상황이 아니면 깊은 비교를 주로 활용하고 있어요.

해당 코드들 또한 깊은 비교로 처리하면 좋을 것 같은데 어떠신가요?

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +    }
P2;

유저 입장에서 유효성 검사를 한다면 어떤 것들을 적용 할 수 있을까요?
추가로 적용해보면 좋을 것 같아요.

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +      console.log("")
ask;

요 로그는 무엇인가요?

2024-11-10 11:35 UTC, hansen-dev commented on src/index.js
> +const ARR_LAST_IDX = -1
해당 값을 상수로 관리하는 것 좋네요!

2024-11-13 09:11 UTC, waterhumanB commented on src/index.js
> +play();
네 설정도 확인해 보겠습니다.

2024-11-13 09:12 UTC, waterhumanB commented on src/index.js
> +async function play() {
10라인으로 줄이려고 일단 함수로 분리해서 다시 구현해봤습니다.

2024-11-13 09:13 UTC, waterhumanB commented on src/index.js
> +  if(resetGame != "yes" && resetGame != "no") {
이부분도 확인해서 깊은 비교로 처리했습니다!

2024-11-13 09:14 UTC, waterhumanB commented on src/index.js
> +    }
이부분이 제일 고민이 많았고, 처음엔 1~50 이외의 숫자만 생각했는데, 생각해 보니까 숫자가 아닐때, 빈값일때, 동일한 값을 넣엇을때, null 같은 값을 넣었을때 생각이나서 함수로 분리해서 구현했습니다.

2024-11-13 09:14 UTC, waterhumanB commented on src/index.js
> +      console.log("")
단순하게 메세지에서 한칸 띄우려고 넣었는데 빼주었습니다.

2024-11-13 09:15 UTC, waterhumanB commented on src/index.js
> +const ARR_LAST_IDX = -1
매직함수라는게 갑자기 생각나서 공통으로 쓰이는 숫자들을 상수로 관리했습니다!

2024-11-15 02:03 UTC, merged