Mission 2
waterhumanB/js-number-up-and-down pull request #2
Opened 2024-11-18 16:49 UTC by waterhumanB

UI와 Domain을 기준으로 제 생각대로 분리했습니다. 나름 생각해서 기준으로 잡은 것은 터미널에 나오는 메세지를 기준으로 UI로 생각했고, 유효성 검사, 랜덤값 생성 등 필요한 기능들을 Domain으로 분리 했습니다. 

이번 구현 과정에서는 유효성 검사를 최소한으로 진행했고, 최소한이라기 보단, 확실하고 보장된 값에만 통과되게 했습니다. 
아쉬운 점은 이번에도 코드 구현에 급급해서, 클래스나 클로저에 전혀 생각을 못했다... 입니다... 저도 모르게 사용했겠지만, 의식해서 사용하지 못한점이 아쉽네요.

궁금한것
1. 멘토님이 생각하셨던 UI와 Domain 기준이 저와 어떻게 다른지 궁금합니다.
2. 유효성 검사를 보장된 값에만 통과되게 구현했는데, 이것도 사실 기준이라는게 있는 건지 궁금합니다.
3. `domain/` 하위의 모듈은 `view/` 하위의 모듈을 의존하지 않아야 한다. 이 말의 뜻이 UI와 Domain의 두 로직은 무관하고, UI가 바뀌어도 Domain 로직은 영향을 주지 않고 원하는 계산값(?)만 준다. 또는 UI는 유저와 상호작용만 담당하고, Domain은 유효성 검사라던가 비즈니스 로직만 담당한다. 이런 느낌으로 이해하고 있습니다. 이렇게 분리하는 이유는 테스트나 재사용성, 코드의 기능을 분리함으로써 유지보수에 편함. 제가 아는 선에서는 이정도 인거 같습니다. 기업에 가면 코드양이 많아 지니까 연습한다고 생각해서 구현했는데, 부족한게 있는지와 제가 놓친게 뭐가 있을까 궁금합니다.

2024-11-20 23:40 UTC, hansen-dev requested changes
수인님 코드 잘 보았어요!

수인님이 말씀하신 기준이 완전 다른 것은 아니지만 조금 더 고민해보셨으면 하는 부분이 있어요.

혹시 MVC 패턴이라고 아시나요?

- 모델 -> 데이터와 관련된 로직을 처리하는 곳 (모델은 뷰를 몰라야함)
- 뷰 -> 입력, 출력과 관련된 로직을 처리하는 곳 (뷰는 모델을 몰라야함)
- 컨트롤러 -> 뷰와 모델의 중간에서 비즈니스 로직을 처리하는 곳

![image](https://github.com/user-attachments/assets/d0b663d3-19f0-40e9-bfd5-be48609684b3)

MVC 패턴을 FM대로 쓰지 않더라도, 이와 비슷한 고민을 담은 아키텍쳐, 비슷한 패턴을 프론트엔드 백엔드에서 많이 사용되고 있어요.

이러한 개념이 왜 나왔는지? 우리의 과제에선 어떻게 활용해볼 수 있을지? 고민해보시고 다시 구조를 잡아보시면 좋을 것 같아요.

2024-11-20 23:40 UTC, hansen-dev commented on domain/getRandomValue.js
> +export default getRandomValue
eof;

요것 쓰윽 챙겨주세요!

2024-11-20 23:40 UTC, hansen-dev commented on domain/getRandomValue.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
소소하지만 
```suggestion

  return Math.floor(Math.random() * (max - min + 1)) + min; 
```

2024-11-21 11:45 UTC, hansen-dev commented on src/index.js
> +import startGame from "../view/startGame.js"
여기선 view, domain import 무엇이던 가능

2024-11-21 11:45 UTC, hansen-dev commented on src/index.js
> +import playGame from "../view/playGame.js"
domain import는 한번만 할 것.

2024-11-21 11:45 UTC, hansen-dev commented on view/playGame.js
> +import readLineAsync from "./readLineAsync.js";
view에선 domain과  / src/index import 하지 말 것

2024-11-21 11:45 UTC, hansen-dev commented on domain/getRandomValue.js
> +function getRandomValue(min, max) {
domain에선 view, src/index import 하지 말 것

2024-11-21 11:45 UTC, hansen-dev commented on view/playGame.js
> +function evaluateGuess(answer, randomNum, inputValue, max) {
뷰에선 게임 로직 판단 하지 말 것

2024-11-23 19:13 UTC, waterhumanB commented
ui와 domain 로직의 분리에만 집중했습니다. ui로직과 domain 로직에 영향이 없고, MVC 패턴이 정답이 아니라고 하셔서, 일단은 index.js 안에 각 domain과 ui를 합친 컨트롤러 같은 로직을 만들어 사용했습니다. 고민이였던거는 그냥 이게 맞나?? 계속 이런 의문이 들었습니다. 크게 고민해보지 않았던 것이여서, ui와 domain이 영향이 가지 않게 분리를 하자에 집중 했습니다.

ui로직과 domain로직은 프론트,백엔드이 있다면, 프론트는 UI에 관련된 로직과 입출력을 담당한다. UI 관련 로직이라고 하면, 대표적으로 유효성 검사는 이메일 로그인으로 예를 들면 @와 . 등의 여부 등을 input값을 받아 바로 표시를 할 수 있다, 하지만 이것을 서버에서도 관리를 할 수 있지만, 사용자에게 좀 더 편리하게? 사용할 수 있다. 백엔드 로직은 프론트에서 받은 데이터를 바탕으로 로직을 구현하며, UI와 로직과 별게로 영향을 받지 않고 작동을 해야한다. 이부분이 domain 부분이다. 간단하게 이해한것을 적어 봤습니다. 앞으로도 고민하고 생각해야할 부분이 될거 같습니다.

2024-11-25 10:34 UTC, hansen-dev reviewed
안녕하세요 수인님!

제가 오해의 여지가 있게 전달을 드렸던 부분이 있는 것 같네요 ㅠㅠ

>  ui로직과 domain 로직에 영향이 없고, MVC 패턴이 정답이 아니라고 하셔서

ui 로직과 domain 로직에 영향이 없는 것은 맞으나,
MVC 패턴이 정답이 아니라고 말한 것은 아니였어요. MVC 외에도 다양한 방법이 있다고 말하고 싶었어요.
(이렇게 말했던 이유는 MVC 패턴만이 정답이라고 생각하실까 하여 말씀 드렸던 것이었어요.)

현재 상황에서는 MVC 패턴을 사용해도 좋아요!!

해당 게임에서 MVC 패턴을 사용했을 떄 아래의 장점을 가지고 있어요.

1. 게임 상태 관리
- 현재는 상태가 여러 함수에 분산되어있고, 이 상태의 흐름을 파악하기가 용이하지 않아요. MVC 패턴을 사용하여 Model 부분에 상태를 모아 관맇한다면 상태 변경의 일관성 뿐 아니라 추적 가능한 코드를 만들 수 있게 돼요.

2. 게임 규칙 및 UI 변경 용이
- 비즈니스 로직(Model or Domain)과 UI(View)를 분리함으로 게임 규칙 변경 시엔 Model만 UI 변경 시에 View 만 수정하면 돼요.
이런 구조적 개선은 코드 품질을 높일 뿐 아니라, 이후 기능 확장이나 유지보수성을 높일 수 있게 돼요.
그 외에 관심사 분리에도 용이하구요.


아래의 기준으로 MVC를 어떻게 나누어 만들면 좋을지 고민해보시면 좋을 것 같아요.
1. Model
  - 게임의 상태와 비즈니스 로직을 캡슐화
  - 유효성 검증 로직을 모델 내부로 이동
  - 상태 변경에 대한 책임을 가짐

2. Controller
  - Model과 View 사이의 중재자 역할
  - 게임 진행 흐름 제어
  - 사용자 입력을 모델에 전달하고 결과를 뷰에 전달

3. View
  - 순수하게 입출력만 담당
  - 비즈니스 로직이나 상태를 포함하지 않음


간단하게 만들어본 MVC 패턴의 코드에요.
```
// models/Game.js
class Game {
  constructor(min, max, maxAttempts) {
    this.min = min;
    this.max = max;
    this.maxAttempts = maxAttempts;
    this.answer = this.generateRandomNumber();
    this.attempts = [];
    this.status = 'PLAYING'; // PLAYING, WON, LOST
  }

  generateRandomNumber() {
    
  }

  makeGuess(guess) {
    
  }

  validateGuess(guess) {
  }
}

// controller
class GameController {
  constructor(view) {
    this.view = view;
    this.game = null;
  }

  async start() {
    const config = await this.view.getGameConfig();
    if (!config) return;

    this.game = new Game(config.min, config.max, config.maxAttempts);
    this.view.displayGameStart(this.game.min, this.game.max);
    
    await this.playGame();
  }

  async playGame() {
    while (this.game.status === 'PLAYING') {
      const guess = await this.view.getGuess();
      const result = this.game.makeGuess(guess);
      
      if (!result) {
        this.view.displayError('Invalid input');
        continue;
      }

      this.view.displayResult(result);
    }

    const playAgain = await this.view.askPlayAgain();
    if (playAgain) {
      await this.start();
    }
  }
}


// View
class ConsoleView {
  constructor(readline) {
    this.readline = readline;
  }

  async getGameConfig() {

  }

  async getGuess() {

  }

  displayGameStart(min, max) {

  }

  displayResult({ result, attempts }) {
    switch (result) {
      case 'UP':
        console.log('업');
        break;
      case 'DOWN':
        console.log('다운');
        break;
      case 'CORRECT':
        console.log(`정답!\n축하합니다! ${attempts.length}번 만에 맞추셨습니다.`);
        break;
      case 'EXCEEDED':
        console.log(`${attempts.length}회 초과! 숫자를 맞추지 못했습니다!`);
        break;
    }
    console.log('이전 추측:', attempts.join(', '));
  }

  // 기타 등등
}
```

2024-11-25 10:34 UTC, hansen-dev commented on domain/domain.js
> +  if (lastGuess === randomNum && inputValue <= max) return "CORRECT"
ask;

inputValue가 max보다 넘는 경우에 대한 고려는 필요 없을까요?

2024-11-25 10:34 UTC, hansen-dev commented on domain/domain.js
> +export function validateMinMax(input) {
단순 궁금증!

만약 min, max를 따로 받게 한다면 어떻게 만들 수 있을까요?

2024-11-25 10:34 UTC, hansen-dev commented on domain/domain.js
> +    ) {
P5;

저는 논리 연산자가 여러개가 얽혀있을 때 기대 결과값이 한눈에 안들어와 시간도 많이 잡아먹고, 실수하는 경우가 많이 있더라구요.

이런 경우에는 코드가 길어지더라도 맥락에 맞게 나누어 봐도 좋을 것 같아요!

```suggestion
    if (input === '' || input === null || input === undefined) return;
    
    if (input < min) return;
    
    if (input > max) return;
    
    if (!answer.includes(Number(input))) return;
    
    return Number(input);
```

2024-11-25 15:53 UTC, waterhumanB commented on domain/domain.js
> +  if (lastGuess === randomNum && inputValue <= max) return "CORRECT"
validateInput 함수에서 max보다 넘는 걸 고려해서 저부분은 업,다운,정답만 고려해서 사용했었습니다.

2024-11-25 15:54 UTC, waterhumanB commented on domain/domain.js
> +export function validateMinMax(input) {
따로 받게 한다는게 min과 max의 개별로 로직을 구현하라는 말씀이신건가요?

2024-11-25 15:55 UTC, waterhumanB commented on domain/domain.js
> +    ) {
코드 가독성 생각해서 로직 구현하겠습니다. and 연산자로 작성할때도 저도 약간 헷갈려 했던게 생각났습니다.

2024-11-26 19:37 UTC, waterhumanB commented
멘토님 예시로 주신 MVC 클래화한거 보면서 제 나름 해석해서 구현했습니다. 저는 클래스를 전혀 사용하지 않아서 생각보다 너무 오래 걸렸습니다.... 오래걸렸던 이유 중 하나는 익숙하지 않은데 한번에 하려고 해서 머리에 쥐가났고, 월요일에 리뷰 주셨을때 손도 못대고 다음날에 구현을 시작했습니다. 함수를 만들듯이 처음부터 하나씩 구현해서 콘솔로 테스트 해보면서 하느라 많이 늦었던거 같아요. 그래도 클래스를 사용하면서 클래스 안에 구조들이 좀 이해가 되고 어떻게 사용해야 하는지 감이 조금 잡혀서 나름 괜찮은 수확같습니다. 그래도 여전히 많은 연습이 필요하다고 느끼고 있어요.

```
1. 게임 상태 관리
현재는 상태가 여러 함수에 분산되어있고, 이 상태의 흐름을 파악하기가 용이하지 않아요. MVC 패턴을 사용하여 Model 부분에 상태를 모아 관맇한다면 상태 변경의 일관성 뿐 아니라 추적 가능한 코드를 만들 수 있게 돼요.

2. 게임 규칙 및 UI 변경 용이
비즈니스 로직(Model or Domain)과 UI(View)를 분리함으로 게임 규칙 변경 시엔 Model만 UI 변경 시에 View 만 수정하면 돼요.
이런 구조적 개선은 코드 품질을 높일 뿐 아니라, 이후 기능 확장이나 유지보수성을 높일 수 있게 돼요.
그 외에 관심사 분리에도 용이하구요.
```

첫 번재 상태관리에 대해서 react로 개발했을때 props나 상태관리 툴을 사용해서 상태관리를 했더라면, 저는 처음 함수로 구현했을때 어떠한 상태값도 관리 하지 않았고, 단순히 순서에 맞게 함수를 구현해서 사용 했습니다. 필요한 값들을 변수화 시켜서 관리를 했던게 클래스를 사용해서 model 클래스에 파라미터를 최소화할 수 있었던거 같아요. 그래도 아쉬운 부분은 controller 처음에 start() 메서드에서도 let으로 변수를 저장해서 사용하긴 했는데, 이부분은 로직을 제가 조금 잘못 구현한건지 아니면 다른 방법이 있었는지? 이런 의문이 들었습니다. 그 외에 react도 처음에 클래스형으로 구현한게 이러한것 때문인건가 생각 들고 react에서는 앞에 말했던 props나 상태관리 툴이 있어 함수형으로 이제 완전히 자리잡게 된건가 이런 생각도 들었는데, 아직 찾아보지는 못했고, 앞으로 고민 해보고 생각도 해보고 찾아봐야 할것같습니다.

두 번째 부분에서는 전에 함수로 구현했을 때는 약간 어거지로 구현했다고 생각했는데, 클래스로 구현하니 좀 더 분리된게 잘 느껴지는거 같아요. 그리고 controller에서 constructor에 view는 초기화하고 game은 초기화를 안했던게 의문이 였는데, 그래서 따로 static으로 빼서 메서드를 사용하기도 했고, 이부분은 view는 ui로 먼저 초기값을 받아야하기 때문에 항상 필요하기 때문인거 같고, game은 view로직을 통해 받은 값으로 초기화된 상태에서 생성하기 때문에 처음부터 초기화할 필요가 없다 라고 생각했습니다. 그래서 아직 사용자에게 값을 받지 않고 초기화 해놓으면 두번 초기화 하는거라 불필요한 메모리가 쓰게 되는건가? 이런 생각도 드는데, 정확히 어떤건지 궁금합니다.

이것 외에 변수명에 대한 고민도 생겼습니다. 멘토님이 예시로 주신 MVC 패턴에 메서드 명을 보니 좀더 이해하기 쉽다는 생각도 들었네요. 이부분도 많이 연습을 해야할것 같습니다.

2024-11-27 20:35 UTC, waterhumanB commented
불필요한 코드는 모두 지웠고, 코드 포맷팅도 했습니다. 코드를 좀 더 보기 좋게 가독성있게 약간의 수정을 했습니다.

유효성 검사 부분에서 null을 받아 그 값을 가지고 유효성 검사에 대한 실패를 판단했었습니다.

https://www.slash.page/ko/libraries/common/assert/src/assert.i18n
https://ko.javascript.info/custom-errors

이런것도 찾아보니 에러에 대한 출력 값은 모두 메세지를 출력하고 있었고, 물론 null값을 받아서 에러 메세지를 사용자에게 보여주고 있지만, 코드만 봤을 때 왜 null을 왜 줄까? 라는 의문이 들 수 있겠다는 생각도 들었습니다. 

그래서 단순하게 "error"라는 값을 리턴하게 했고, 이 값은 다른곳에도 쓰일 것 같아 상수화 시켜 사용했습니다.
이렇게 되면 ERROR라는 상수 값이 정확히 어떤 메세지인지는 잘 모를 수 있지만 무엇인가 잘못 했을 때 에러값을 넘겨 주는 구나 라고 생각할 수 있게 될 것 같네요.

그리고 게임을 실행을 했을때 약간의 버그라고 해야하나 조금 문제가 있어서 그것도 조금 수정해서, 이제는 게임이 완벽하게?는 아니고 문제 없이 돌아 가는 것 같습니다.

2024-11-29 07:37 UTC, hansen-dev approved these changes
좋아요! 3단계로 꼬우 해보시죠!

2024-11-30 06:45 UTC, closed without merging